const INCORRECT_DATA = 400;
const WRONG_EMAIL_OR_PASSWORD = 401;
const NOT_FOUND = 404;
const DEFAULT_ERROR = 500;
const DUPLICATE_ERROR_CODE = 409;
const NO_RIGHTS_TO_DELETE = 403;
const MONGO_DUPLICATE_ERROR_CODE = 11000;

module.exports = {
  INCORRECT_DATA,
  NOT_FOUND,
  DEFAULT_ERROR,
  DUPLICATE_ERROR_CODE,
  WRONG_EMAIL_OR_PASSWORD,
  NO_RIGHTS_TO_DELETE,
  MONGO_DUPLICATE_ERROR_CODE,
};
